# LLM provider and models to use
llm:
  provider: 'openrouter'
  base_url: 'https://openrouter.ai/api/v1'

  models:
    context_builder: 'google/gemini-flash-1.5'
    reviewer: 'google/gemini-1.5-pro'

# --- Context building settings ---
max_context_files: 25

# --- File filtering settings ---
filtering:
  ignored_extensions:
    - '.dll'
    - '.so'
    - '.exe'
    - '.png'
    - '.jpg'
    - '.jpeg'
    - '.gif'
    - '.svg'
    - '.min.js'
    - '.lock'
    - '.zip'
    - '.o'
    - '.a'
    - '.obj'
    - '.lib'
    - '.pdb'

  ignored_paths:
    - 'node_modules'
    - 'venv'
    - '.venv'
    - '.git'
    - '__pycache__'
    - 'dist'
    - 'build'
    - 'target'
    - '.next'
    - '.pytest_cache'

  ignored_patterns:
    - 'Designer.cs'
    - 'package-lock.json'
    - 'yarn.lock'
    - 'pnpm-lock.yaml'
    - 'package.json'

# Keywords to identify and ignore test files

test_keywords: ['test', 'spec', 'fixture']

# --- Reviewer settings ---
# Default focus areas if not specified in CLI.
# If omitted, defaults to "LogicError" only.
review_focus:
  - 'Security'
  - 'Performance'
  - 'LogicError'
  - 'CodeStyle'

# Custom rules for the reviewer agent.
review_rules:
  - 'All public functions must have a docstring.'
  - 'Pay close attention to potential N+1 query problems.'
