llm:
  provider: 'openai'
  model_context: 'gpt-4o'
  model_review: 'gpt-4o'

filtering:
  ignored_extensions:
    - '.dll'
    - '.so'
    - '.exe'
    - '.png'
    - '.jpg'
    - '.jpeg'
    - '.gif'
    - '.min.js'
    - '.lock'
    - '.zip'
    - '.o'
    - '.a'
    - '.obj'
    - '.lib'
    - '.pdb'

  ignored_paths:
    - 'node_modules'
    - 'venv'
    - '.venv'
    - '.git'
    - '__pycache__'
    - 'dist'
    - 'build'
    - 'target'


review_rules:
  - 'Pay close attention to potential race conditions in async code.'
  - 'All public functions must have a docstring.'
  - 'Avoid using magic numbers; define them as constants.'
