[project]
name = "codereviewagent"
version = "0.1.0"
description = ""
authors = [
    {name = "Mykhailo",email = "mykhailo.ulanovych@exilion.com"}
]
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "openai (>=1.95.1,<2.0.0)",
    "instructor (>=1.9.2,<2.0.0)",
    "gitpython (>=3.1.44,<4.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "pygithub (>=2.6.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
