import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import {
	filterFilesByPattern,
	filterTestFiles,
	isGeneratedFile,
	isFrontendNoiseFile,
	isLockfile,
	shouldIgnorePath,
} from '../../src/git/filtering.js';

describe('filtering', () => {
	it('filters test files by path segment', () => {
		const result = filterTestFiles(
			{
				'src/services/UserService.cs': '...',
				'src/tests/UserService.Tests.cs': '...',
				'src/spec/component.spec.js': '...',
			},
			['test', 'tests', 'spec'],
		);

		expect(result).toEqual({
			'src/services/UserService.cs': '...',
		});
	});

	it('filters common dotted test filenames', () => {
		const result = filterTestFiles(
			{
				'src/app.ts': '...',
				'src/app.test.ts': '...',
				'src/component.spec.tsx': '...',
			},
			['test', 'spec'],
		);

		expect(result).toEqual({
			'src/app.ts': '...',
		});
	});

	it('filters ignored filename patterns', () => {
		const result = filterFilesByPattern(
			{
				'src/index.ts': '...',
				'package-lock.json': '...',
			},
			['package-lock.json'],
		);

		expect(result).toEqual({
			'src/index.ts': '...',
		});
	});

	it('matches ignored paths and extensions', () => {
		expect(
			shouldIgnorePath('node_modules/pkg/index.js', {
				ignoredExtensions: ['.png'],
				ignoredPaths: ['node_modules'],
				ignoredPatterns: [],
			}),
		).toBe(true);

		expect(
			shouldIgnorePath('assets/logo.png', {
				ignoredExtensions: ['.png'],
				ignoredPaths: [],
				ignoredPatterns: [],
			}),
		).toBe(true);
	});

	it('detects known lockfiles', () => {
		expect(isLockfile('package-lock.json')).toBe(true);
		expect(isLockfile('src/packages.lock.json')).toBe(true);
		expect(isLockfile('src/app.ts')).toBe(false);
	});

	it('detects frontend noise files', () => {
		expect(isFrontendNoiseFile('src/components/Button.stories.tsx')).toBe(true);
		expect(isFrontendNoiseFile('src/components/Button.snap')).toBe(true);
		expect(isFrontendNoiseFile('dist/app.js.map')).toBe(true);
		expect(isFrontendNoiseFile('src/components/Button.tsx')).toBe(false);
	});

	it('detects generated files by path pattern', async () => {
		expect(
			await isGeneratedFile('/repo', 'src/services/crm-api-schema.ts', {
				excludeFromReview: true,
				logExcluded: true,
				ignoredPaths: ['__generated__'],
				ignoredPatterns: ['api-schema'],
				contentMarkers: [],
			}),
		).toBe(true);
	});

	it('detects generated files by content marker', async () => {
		const repoPath = await mkdtemp(path.join(tmpdir(), 'code-review-agent-filtering-'));

		try {
			await writeFile(
				path.join(repoPath, 'client.ts'),
				'/* This file was auto-generated by openapi-typescript. */\nexport const value = 1;\n',
				'utf8',
			);

			expect(
				await isGeneratedFile(repoPath, 'client.ts', {
					excludeFromReview: true,
					logExcluded: true,
					ignoredPaths: [],
					ignoredPatterns: [],
					contentMarkers: ['auto-generated'],
				}),
			).toBe(true);
		} finally {
			await rm(repoPath, { recursive: true, force: true });
		}
	});
});
